### PR TITLE
Update civicpy to work with the new CIViC API

### PR DESCRIPTION
**Pull request by korikuzma**
This is essentially the same as #127 , but excludes molecular profiles. I added some additional fields to the GraphQL queries since we needed this information in MetaKB. 

@susannasiebert and @acoffman , once this gets merged would we be able to create a new pypi dev release that we can use in MetaKB?

### CODE REVIEW

**Comment by susannasiebert** [comment]
I think this looks fine. We need to setup a github action to actually run the tests on github.

In regards to a release, I'm going to be on vacation starting tomorrow and I'm at a conference today so I don't think I can make this release until after I return in three weeks. I also checked on pypi and it looks like I don't have enough permissions to add another maintainer. I think Alex would need to add either yourself or Adam as a maintainer so that you can make a new release if you need it sooner.

**Comment by korikuzma** [comment]
@susannasiebert I can make a separate issue for the GitHub action. 

@ahwagner would you be able to add either @acoffman or I as a maintainer? I'd like to get a dev release sooner that when @susannasiebert returns, if possible.

**Comment by korikuzma** [comment]
Forgot to update version. Set it to `2.0.dev0`. Let me know if it should be something else @susannasiebert or @acoffman

**Review by acoffman — APPROVED** [review]
LGTM

**Pull request merged**
