### PR TITLE
Partial support for issue 65

### PR DESCRIPTION
**Pull request by ahwagner**
This PR introduces provenance information for most first-class CIViC entities. Genes are an exception, additional work is ongoing on CIViC-server to address.

### CODE REVIEW

**Comment by ahwagner** [comment]
Hey @susannasiebert. I plan to release rc3 today with the content from this PR (and a related PR to document these changes) to get RTD working prior to having reviewers look at it. We can add in Genes (which requires the discussed changes over at civic-server) later this week / early next as rc4.

**Comment by susannasiebert** [comment]
@ahwagner https://github.com/griffithlab/civic-server/pull/556 should take care of the civic-server side of things.

**Comment by ahwagner** [comment]
😲 
Wow, that was fast. Okay, then I'm not going to merge this yet, will roll in the `Gene` changes and documentation too. Stay tuned.

**Comment by ahwagner** [comment]
Err, actually–this isn't in production yet 🤦‍♂. So, merging as-is, will open up separate PR for Genes down the stretch.

**Pull request merged**
